### ISSUE TITLE
Add testcase coverage for LogAddCommand / Parser, UG documentation for LogAdd Function

### ISSUE THREAD

**Issue by gerteck** [AY2324S2-CS2103T-T09-3/tp#100]
Currently no testcase coverage for both `LogAddCommand` and `LogAddCommandParser` exists.

To add UG documentation for LogAddCommand under 

```
### 3.2 Log Management

#### Adding a log: `logAdd`

TODO
```

**Comment by soons1** [comment]
Test coverage for LogAddCommand is added, still needs to be done for LogAddCommandParser
