### ISSUE TITLE
Add testcase coverage for LogEditCommand/Parser, UG documentation for LogEdit Function

### ISSUE THREAD

**Issue by gerteck** [AY2324S2-CS2103T-T09-3/tp#101]
Currently no testcase coverage for both `LogEditCommand` and  `LogEditCommandParser` exists.

To add UG documentation for LogEditCommand under 

```
### 3.2 Log Management

#### Editing a log: `logEdit`

TODO
```

**Comment by soons1** [comment]
I can work on the LogEditCommandTest as I will be working on updating the timeServed in LogEditCommand
