### ISSUE TITLE
Pair volunteer and elderly befriendee contacts

### ISSUE THREAD

**Issue by CJerrong** [AY2324S2-CS2103T-T09-3/tp#11]
As a voluntary organisation manager, I can pair volunteer and elderly befriendee contacts, so that I can keep track of which volunteers are paired with which elderly befriendees easily, and relay relevant information accordingly.

**Comment by soons1** [comment]
- Befriendee and Volunteer objects will have a corresponding Volunteer/Befriendee as a field
- Pair command will update the bidirectional association between Befriendee and Volunteer
