### ISSUE TITLE
Add testcases for Person, LogStore, PersonStore classes and Update UG/DG for the Model class.

### ISSUE THREAD

**Issue by CJerrong** [AY2324S2-CS2103T-T09-3/tp#111]
- Currently lacking testcases for new fields added to `Person` class.
- Currently lacking testcases for `LogStore` and `PersonStore` classes.
- DG for the Model class has to be updated to include the new fields in Person class

**Comment by gerteck** [comment]
Will do manual testing which has higher yield instead
