### ISSUE TITLE
[PE-D][Tester D] I can add identical person to the list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-3/tp#131]
I can add totally identical person.

![image.png](https://raw.githubusercontent.com/wallacexuhanxiao/ped/main/files/c01470d3-12e6-4abd-9b48-727dbee7a912.png)

Expected to get an error message.

It may give us some unclear information when we are using find by name command. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: wallacexuhanxiao/ped#1

**Comment by chaaaaun** [comment]
Consolidating all "duplicate person" issues into this issue. In view of the feature freeze, I think the best we can do here is to acknowledge the issue in the UG and suggest workarounds.

**Comment by gerteck** [comment]
> Consolidating all "duplicate person" issues into this issue. In view of the feature freeze, I think the best we can do here is to acknowledge the issue in the UG and suggest workarounds.

Let me clarify if we can fix this duplicate issue

**Comment by gerteck** [comment]
https://github.com/nus-cs2103-AY2324S2/forum/issues/766

**Comment by gerteck** [comment]
![image](https://github.com/AY2324S2-CS2103T-T09-3/tp/assets/111064611/1c060708-0d56-4f26-9b1e-9a37483271fc)
