### ISSUE TITLE
[PE-D][Tester E] General Error Message Handling used

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#134]
For example, if I am missing fields in add, it is not clear exactly what fields I am missing and it may be hard for the users to read the format and derive the difference in formatting. It is easier for the app to flag out what is missing, thus improving user experience. 

To replicate my error message, I ran the following command `add n/Betsy Crowe r/befriendee t/friend e/betsycrowe@example.com`

Below is the screenshot of the error message shown on the interface:

![image.png](https://raw.githubusercontent.com/yleeyilin/ped/main/files/dc43506d-234a-4299-8b21-94ec905fd425.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: yleeyilin/ped#2

**Comment by chaaaaun** [comment]
Valid, can investigate how hard it would be to give custom error messages for different flags. Some flags already do it after all. Although, in the current case, the tester is missing two entire parameters, which should be evident if the user guide or command format is followed.

**Comment by gerteck** [comment]
![image](https://github.com/AY2324S2-CS2103T-T09-3/tp/assets/111064611/d3e6d5a2-1c4f-47dc-a6b5-7064c18ec4f1)

Quite sure error message cannot be more specific, unforunately
