### ISSUE TITLE
[PE-D][Tester E] Invalid field validation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#139]
As a fast typist, I may miss out on the correct phone numbers. The validation check of the phone numbers can be stricter to help me catch these errors. However, Elder Scrolls do not currently validate the phone numbers for certain invalid phone numbers. 

Command to replicate:
`add n/John Doe r/befriendee p/982 e/johnd@example.com a/John street, block123, #01-01`

Output:

![image.png](https://raw.githubusercontent.com/yleeyilin/ped/main/files/c2b258c9-f85d-431d-aac2-c4d595dc9684.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: yleeyilin/ped#6

**Comment by gerteck** [comment]
Fast Typist does not imply Inaccuracy. 

It is 2024, we should not be assuming what phone numbers can or cannot be.

**Comment by chaaaaun** [comment]
[https://en.wikipedia.org/wiki/Category:Telephone_numbers_by_country](https://en.wikipedia.org/wiki/Category:Telephone_numbers_by_country)
