### ISSUE TITLE
[PE-D][Tester D] Find command don’t reject invalid r/ inputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#140]
# Buggy input
![image.png](https://raw.githubusercontent.com/wallacexuhanxiao/ped/main/files/3ed4baff-3a5b-4461-a675-197e8f817e8e.png)

# Result
![image.png](https://raw.githubusercontent.com/wallacexuhanxiao/ped/main/files/f1fbf98f-142b-430a-9aab-da809681f00c.png)

Expect the application to prohibit the invalid input in r/ instead of ignoring it.

Maybe add a constraint to check through the input?

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: wallacexuhanxiao/ped#4

**Comment by chaaaaun** [comment]
Valid.

**Comment by gerteck** [comment]
TODO: Clarify in UG to be more specific on how the FIND command works
