### ISSUE TITLE
[PE-D][Tester D] Find command do react to invalid input and list 0 person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#142]
# Buggy input
![image.png](https://raw.githubusercontent.com/wallacexuhanxiao/ped/main/files/629bb9b8-9ffa-48ca-a5ee-3da63b7c9138.png)

# Buggy output
![image.png](https://raw.githubusercontent.com/wallacexuhanxiao/ped/main/files/96f4b7cc-2328-4a1e-8ede-e686b8e3c6f5.png)

## Can add an exception to handle such issue.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: wallacexuhanxiao/ped#5

**Comment by chaaaaun** [comment]
From a user perspective, this would indeed seem like a bug. In the backend, the Parser in the backend likely interprets this as a generic `KEYWORD` and not a flag. Possibly solution could be to rework the Parser to detect `[letter]/` as a flag, but not sure how much work that is.

Also have to consider that people could legitimately have `p/123028` be their name nowadays, in which case that would be a valid search.
