### ISSUE TITLE
[PE-D][Tester D] Doesn't handle the integer overflow

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-3/tp#156]
# When the inputting number is big, the application don't recognize my integer input as an integer.

![image.png](https://raw.githubusercontent.com/wallacexuhanxiao/ped/main/files/0ed3d495-ab54-4f2d-8f31-17c9ec032c50.png)

# Expect to see error message about input number is too big instead of not an integer.

## I suggest you can change the type of the input into Long so that the problem can be fixed

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: wallacexuhanxiao/ped#9

**Comment by chaaaaun** [comment]
Duplicate of #163.
