### ISSUE TITLE
[PE-D][Tester A] Dates with year as 0000 marked as 'invalid date format' despite following YYYY-MM-DD

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#164]
![image.png](https://raw.githubusercontent.com/brennalaurentan/ped/main/files/1a7591e8-d869-4195-91f9-740f78714715.png)

When I tried to edit the logs with date 0000-12-12, 0000 got denied as an acceptable year, with the user message stating that it's 'invalid date format', although the date is in fact in the correct format requested. Perhaps you might want to allow this date to be entered as it is in the correct format, or state an acceptable date range ('0001-01-01 onwards') ?

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: brennalaurentan/ped#4

**Comment by gerteck** [comment]
Valid Suggestion.

**Comment by chaaaaun** [comment]
Java does not allow a year 0000, as it only starts from 1AD, which is 0001. We should just mention the range in the UG.
