### ISSUE TITLE
[PE-D][Tester A] Badges on project website not linked to your repo's stats

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#166]
![image.png](https://raw.githubusercontent.com/brennalaurentan/ped/main/files/24be4cff-1ab5-4c68-a707-ccb9eb0b7545.png)

Not related to user guide! But just wanted to flag that the badges on your website's home page are linked to the course repo's stats and not your own repo's! Probably need to change the links in the index.md file :)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: brennalaurentan/ped#6

**Comment by gerteck** [comment]
Bless up
