### ISSUE TITLE
[PE-D][Tester E] Find command field acceptance

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#172]
![image.png](https://raw.githubusercontent.com/yleeyilin/ped/main/files/12b5cedc-e09d-4633-9067-370d950387f6.png)

Command to replicate:
`find ale`

It may be useful to allow for find by incomplete name in case the user can't remembers what is the exact name of the contact.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: yleeyilin/ped#18

**Comment by gerteck** [comment]
The intended purpose for find is to bring up the person in the index for easy pairing, and I argue that it fits our use case well, to `search for specific elderly befriendee or volunter befriender`. This feature hence solves stated problem of the intended user, and is well optimized.

Although the suggestion is valid, it does not warrant a medium severity.
