### ISSUE TITLE
[PE-D][Tester E] Glossary missing volunteers and befriendee 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-3/tp#180]
The glossary do not define what is a volunteer and what is a befriendee. 

It is best to define these contact types since befriendee may not be intuitive.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yleeyilin/ped#25

**Comment by gerteck** [comment]
> severity.VeryLow : A flaw that is purely cosmetic and does not affect usage e.g., a typo/spacing/layout/color/font issues in the docs or the UI that doesn't affect usage. Only cosmetic problems should have this label.
