### ISSUE TITLE
Update DG: Instructions for Manual Testing

### ISSUE THREAD

**Issue by gerteck** [AY2324S2-CS2103T-T09-3/tp#187]
![image](https://github.com/AY2324S2-CS2103T-T09-3/tp/assets/111064611/7632d33e-76b5-42be-987d-8b0e5b673740)

**Comment by gerteck** [comment]
Add - soonz
Edit - soonz
Pair - soonz
Unpair - soonz

List - not needed
Find - gt
Delete - soonz
LogAdd - devi
LogEdit - devi
LogDelete -devi 
LogFind - gt
Undo - jr
Redo - jr
Help - noneed
Clear - noneed
Exit - noneed

**Comment by soons1** [comment]
instructions for the following commands are added:
- Add
- Edit
- Delete
- Pair
- Unpair

**Comment by CJerrong** [comment]
instructions for the following commands are added:

* Undo
* Redo

**Comment by gerteck** [comment]
instructions for the following commands are added:

* find
* logfind

**Comment by sdevih** [comment]
instructions for the following commands are added:

- logadd
- logedit
- logdelete
