### ISSUE TITLE
Support `find` command filtering separately for volunteers and befriendees

### ISSUE THREAD

**Issue by chaaaaun** [AY2324S2-CS2103T-T09-3/tp#74]

**Comment by gerteck** [comment]
Current Format:
`find KEYWORD [MORE_KEYWORDS]`

Planned added feature: Filter separately for volunteer and befriendee, while not clearing the other list. This is to faciliate pairing and unpairing operations using the index.

- `find r/volunteer KEYWORD [MORE_KEYWORDS`
- `find r/befriendee KEYWORD [MORE_KEYWORDS`

Action: Will find given person in the list of the respective role.
